// Google Ad Manager rewarded-web integration. VITE_REWARDED_AD_UNIT_PATH must be
// a Google Ad Manager rewarded ad unit path (for example, /1234567/rewarded),
// never an AdSense publisher ID or an AdSense ad-slot ID.
const GPT_URL='https://securepubads.g.doubleclick.net/tag/js/gpt.js';
let gptPromise;let servicesEnabled=false;let activeSession;
const configured=()=>import.meta.env.VITE_AD_PROVIDER==='google-ad-manager'&&/^\/.+/.test(import.meta.env.VITE_REWARDED_AD_UNIT_PATH||'');
const loadGPT=()=>{if(window.googletag?.apiReady)return Promise.resolve(window.googletag);if(gptPromise)return gptPromise;window.googletag=window.googletag||{cmd:[]};gptPromise=new Promise((resolve,reject)=>{const existing=document.querySelector(`script[src="${GPT_URL}"]`);if(existing){existing.addEventListener('load',()=>resolve(window.googletag),{once:true});existing.addEventListener('error',()=>reject(new Error('GPT failed to load')),{once:true});return}const script=document.createElement('script');script.async=true;script.src=GPT_URL;script.onload=()=>resolve(window.googletag);script.onerror=()=>reject(new Error('GPT failed to load'));document.head.appendChild(script)});return gptPromise};
const cmd=(gpt,fn)=>new Promise((resolve,reject)=>gpt.cmd.push(()=>{try{resolve(fn())}catch(error){reject(error)}}));
export const isRewardedAdReady=()=>Boolean(activeSession?.ready);
export const initializeRewardedAd=({onReady,onGranted,onClosed,onUnavailable,onError}={})=>{if(!configured()){onUnavailable?.('Rewarded ads are not configured yet.');return {destroy(){}}}activeSession?.destroy();let slot,service,timeout,reveal,ready=false,granted=false,destroyed=false;const session={ready:false,showRewardedAd(){if(ready&&reveal)reveal()},destroy(){if(destroyed)return;destroyed=true;clearTimeout(timeout);if(service){service.removeEventListener('rewardedSlotReady',readyListener);service.removeEventListener('rewardedSlotGranted',grantListener);service.removeEventListener('rewardedSlotClosed',closedListener);service.removeEventListener('slotRenderEnded',renderListener)}if(slot)window.googletag?.destroySlots([slot]);if(activeSession===session)activeSession=undefined}};const unavailable=message=>{if(destroyed)return;onUnavailable?.(message);session.destroy()};const readyListener=event=>{if(event.slot!==slot||destroyed)return;ready=true;session.ready=true;reveal=()=>event.makeRewardedVisible();onReady?.()};const grantListener=event=>{if(event.slot!==slot||destroyed||granted)return;granted=true;onGranted?.({sessionId:crypto.randomUUID(),points:10,payload:event.payload})};const closedListener=event=>{if(event.slot!==slot||destroyed)return;onClosed?.(granted);session.destroy()};const renderListener=event=>{if(event.slot===slot&&event.isEmpty)unavailable('No rewarded ad is available right now.')};activeSession=session;loadGPT().then(gpt=>cmd(gpt,()=>{service=gpt.pubads();slot=gpt.defineOutOfPageSlot(import.meta.env.VITE_REWARDED_AD_UNIT_PATH,gpt.enums.OutOfPageFormat.REWARDED);if(!slot){unavailable('Rewarded ads are not supported on this device.');return}slot.addService(service);service.addEventListener('rewardedSlotReady',readyListener);service.addEventListener('rewardedSlotGranted',grantListener);service.addEventListener('rewardedSlotClosed',closedListener);service.addEventListener('slotRenderEnded',renderListener);if(!servicesEnabled){gpt.enableServices();servicesEnabled=true}gpt.display(slot);timeout=setTimeout(()=>unavailable('No rewarded ad is available right now.'),15000)})).catch(()=>{onError?.('Advertising service is temporarily unavailable.');session.destroy()});return session};
export const showRewardedAd=session=>session?.showRewardedAd();
export const destroyRewardedAd=session=>session?.destroy();
